Introduction to tensores
@tf.function(way to speed up regular python functions using Gpus with tensoreflows(or TPU)


**introduction to tensors
**

In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
#create tensors with tf.constant()
scalar=tf.constant(7)

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
#creating a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# 3create another matrix
another_matrix=tf.constant([[10,7],
                            [3,2],
                            [7,10]])

In [10]:
another_matrix.ndim

2

In [11]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 7, 10]], dtype=int32)>

In [12]:
# create  a tensor
tensor= tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [13]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
# scalar: a single number
# vector: a number with direction (eg wind speed and direction)
# matrix: a 2 dimentional array of numbers
# tensor: an n-dimentional array of numbers(when n can be any number , a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)



In [16]:
# creating tensors with tf.Variable

In [17]:
changeable_tensor=tf.Variable([10,7])  #value can be chnaged
unchangeable_tensor=tf.constant([10,3]) #value cannot be chnaged
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>)

In [18]:
#lets try change one of the elements in our changeable tensor

changeable_tensor[0].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [19]:
# unchangeable_tensor[0].assign[15]
# vector cannot be changed


**creating random tensors**

In [20]:
# inputs->>numerical encoding-->> patterns/features->>representation o/ps-->>>outputs



In [21]:
#create two random( but the same) tensors

random_1=tf.random.Generator.from_seed(42)  #fixed
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [23]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [25]:
random_3=tf.random.Generator.from_seed(7)
random_3=random_3.normal(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [26]:
random_2==random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [27]:
random_4=tf.random.uniform(shape=(3,2))

In [28]:
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8084254 , 0.52189016],
       [0.46342778, 0.43562353],
       [0.9584453 , 0.28422976]], dtype=float32)>

**Shuffling the order of elements in a tensor**

In [29]:
# SHuffling the order of tensors
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [8,9]])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [30]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [31]:
#fixed tensor
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [ 3,  4],
       [10,  7]], dtype=int32)>

other ways to make tensor





In [32]:
tf.ones(shape=[10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [33]:
tf.zeros(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [34]:
#turn numpy arrays to tensors

#main diff between numpy arrays and tensors is that tenosrs can run on a GPU(much faster)


import numpy as np
numpy_A=np.arange(1,25,dtype=np.float32)

In [35]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [36]:
# passing numpy arrays
A=tf.constant(numpy_A,shape=(2,3,4))

In [37]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)>

In [38]:
B=tf.constant(numpy_A,shape=(3,8))

In [39]:
B

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

In [40]:
#getting imformations from tensors

# --shape tensor.shape
# --rank  tensor.ndim
# --axis or dimension  tensor[0], tensor[1]  
# --size  tf.size(tensor)



In [41]:
# create a rank 4 tensor(4 dimensions)

ran4_tensor=tf.zeros(shape=[2,3,4,5])

In [42]:
ran4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
ran4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [44]:
ran4_tensor.shape,ran4_tensor.ndim,tf.size(ran4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [45]:
tf.size(ran4_tensor).numpy()

120

In [46]:
#indexing tensors
#first two elements ij the rank4 tensor
ran4_tensor[0][0][0][0],ran4_tensor[0][0][0][1]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)

In [48]:
#aggregating tensors
# --condensing them from multiple values down to a similar amount of values

#get the absolute values

D=tf.constant([-7,-10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [49]:
tf.abs(D)  #absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [50]:
# forms of aggregation

# min,max,mean,sum

E=tf.constant(np.random.randint(0,100,size=50))

In [51]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 56,  2, 28, 30, 54, 94,  7, 64, 24, 59, 10, 50, 99, 51, 15, 15,
       55, 29, 72, 74, 30, 15, 45, 45, 66, 80, 94, 44, 91,  6, 66, 55,  1,
       36, 99, 15, 13, 95, 83, 78, 33, 71, 25, 80,  5, 55, 82, 72,  9])>

In [56]:
random_tensor=tf.random.uniform(shape=(1,10),seed=42)
random_tensor

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.65938854, 0.867519  , 0.5677675 , 0.63511133, 0.45259678,
        0.54839706, 0.8635087 , 0.6329788 , 0.9307935 , 0.34391415]],
      dtype=float32)>

In [57]:
tf.size(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [60]:
random_tensor.shape

TensorShape([1, 10])

In [61]:
random_tensor.ndim

2

In [62]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.34391415>

In [63]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9307935>

In [64]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=6.5019755>

variance

In [66]:
import tensorflow_probability as tfp
tfp.stats.variance(random_tensor).numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [76]:
r=tf.constant([1,2,2,3,4,1,2,30],dtype=tf.float32)
r
tfp.stats.variance(r)

<tf.Tensor: shape=(), dtype=float32, numpy=85.734375>

In [78]:
tf.math.reduce_std(r)

<tf.Tensor: shape=(), dtype=float32, numpy=9.259286>