Introduction to tensores
@tf.function(way to speed up regular python functions using Gpus with tensoreflows(or TPU)


**introduction to tensors
**

In [109]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [110]:
#create tensors with tf.constant()
scalar=tf.constant(7)

In [111]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [112]:
scalar.ndim

0

In [113]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [114]:
vector.ndim

1

In [115]:
#creating a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [116]:
matrix.ndim

2

In [117]:
# 3create another matrix
another_matrix=tf.constant([[10,7],
                            [3,2],
                            [7,10]])

In [118]:
another_matrix.ndim

2

In [119]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 7, 10]], dtype=int32)>

In [120]:
# create  a tensor
tensor= tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [121]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [122]:
tensor.ndim

3

In [123]:
# scalar: a single number
# vector: a number with direction (eg wind speed and direction)
# matrix: a 2 dimentional array of numbers
# tensor: an n-dimentional array of numbers(when n can be any number , a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)



In [124]:
# creating tensors with tf.Variable

In [125]:
changeable_tensor=tf.Variable([10,7])  #value can be chnaged
unchangeable_tensor=tf.constant([10,3]) #value cannot be chnaged
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>)

In [126]:
#lets try change one of the elements in our changeable tensor

changeable_tensor[0].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [127]:
# unchangeable_tensor[0].assign[15]
# vector cannot be changed


**creating random tensors**

In [128]:
# inputs->>numerical encoding-->> patterns/features->>representation o/ps-->>>outputs



In [129]:
#create two random( but the same) tensors

random_1=tf.random.Generator.from_seed(42)  #fixed
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [130]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [131]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [132]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [133]:
random_3=tf.random.Generator.from_seed(7)
random_3=random_3.normal(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [134]:
random_2==random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [135]:
random_4=tf.random.uniform(shape=(3,2))

In [136]:
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.68789124, 0.48447883],
       [0.9309944 , 0.252187  ],
       [0.73115396, 0.89256823]], dtype=float32)>

**Shuffling the order of elements in a tensor**

In [137]:
# SHuffling the order of tensors
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [8,9]])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [138]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [139]:
#fixed tensor
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

other ways to make tensor





In [140]:
tf.ones(shape=[10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [141]:
tf.zeros(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [142]:
#turn numpy arrays to tensors

#main diff between numpy arrays and tensors is that tenosrs can run on a GPU(much faster)


import numpy as np
numpy_A=np.arange(1,25,dtype=np.float32)

In [143]:
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [144]:
# passing numpy arrays
A=tf.constant(numpy_A,shape=(2,3,4))

In [145]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)>

In [146]:
B=tf.constant(numpy_A,shape=(3,8))

In [147]:
B

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

In [148]:
#getting imformations from tensors

# --shape tensor.shape
# --rank  tensor.ndim
# --axis or dimension  tensor[0], tensor[1]  
# --size  tf.size(tensor)



In [149]:
# create a rank 4 tensor(4 dimensions)

ran4_tensor=tf.zeros(shape=[2,3,4,5])

In [150]:
ran4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [151]:
ran4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [152]:
ran4_tensor.shape,ran4_tensor.ndim,tf.size(ran4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [153]:
tf.size(ran4_tensor).numpy()

120

In [154]:
#indexing tensors
#first two elements ij the rank4 tensor
ran4_tensor[0][0][0][0],ran4_tensor[0][0][0][1]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)

In [155]:
#aggregating tensors
# --condensing them from multiple values down to a similar amount of values

#get the absolute values

D=tf.constant([-7,-10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [156]:
tf.abs(D)  #absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [157]:
# forms of aggregation

# min,max,mean,sum

E=tf.constant(np.random.randint(0,100,size=50))

In [158]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59, 50, 57, 97, 98, 56, 71, 32, 22, 72, 83, 98, 11, 44, 94, 65, 48,
       81, 19, 11, 76,  5, 24, 29, 17,  5, 55, 99, 93, 51, 59, 24, 99, 83,
        9, 58, 67, 21, 44, 28, 71, 25,  9, 23, 47, 87, 16, 88, 59, 66])>

In [159]:
random_tensor=tf.random.uniform(shape=(1,10),seed=42)
random_tensor

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144,
        0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096]],
      dtype=float32)>

In [160]:
tf.size(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [161]:
random_tensor.shape

TensorShape([1, 10])

In [162]:
random_tensor.ndim

2

In [163]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.21551096>

In [164]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.95471144>

In [165]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=5.208084>

variance

In [166]:
import tensorflow_probability as tfp
tfp.stats.variance(random_tensor).numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [167]:
r=tf.constant([1,2,2,3,4,1,2,30],dtype=tf.float32)
r
tfp.stats.variance(r)

<tf.Tensor: shape=(), dtype=float32, numpy=85.734375>

In [168]:
tf.math.reduce_std(r)

<tf.Tensor: shape=(), dtype=float32, numpy=9.259286>

In [169]:
# positional maximum and minimum

#index of max and min
tf.random.set_seed(42)
f=tf.random.uniform(shape=[40],seed=42)

In [170]:


f

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144,
       0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096,
       0.07745171, 0.57921314, 0.29180396, 0.26718032, 0.37012458,
       0.7161033 , 0.45877767, 0.11764562, 0.21073711, 0.5441973 ,
       0.9898069 , 0.38395858, 0.04683566, 0.8718462 , 0.25881708,
       0.873135  , 0.64698434, 0.41981232, 0.24148273, 0.09550059,
       0.9820819 , 0.1570208 , 0.2997682 , 0.36795306, 0.9453716 ,
       0.11056781, 0.52287626, 0.8305441 , 0.0020721 , 0.9594034 ],
      dtype=float32)>

In [171]:

#frind the index of max
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [172]:

f[tf.argmax(f)]==tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [173]:
#squeezing a tensor(removing all single dimensions)
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [174]:
g_squeezed=tf.squeeze(g)


In [175]:
g_squeezed   #removed all one dimensions

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

**one hot encoding**

In [176]:
# one -hot encoding tensors

#encode categorical data

# create a list

list=[0,1,2,3]  #could be red, green,blue,purple

tf.one_hot(list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [177]:
tf.one_hot(list,depth=4,on_value="75",off_value="07")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'75', b'07', b'07', b'07'],
       [b'07', b'75', b'07', b'07'],
       [b'07', b'07', b'75', b'07'],
       [b'07', b'07', b'07', b'75']], dtype=object)>

In [178]:
# Squaring,log,Square root

tf.square(8)

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [179]:
tf.sqrt(8.0) #method requires non int type

<tf.Tensor: shape=(), dtype=float32, numpy=2.828427>

In [180]:
# tensors and numpy

# tensorflow interacts well with numpy array

a=tf.constant(np.array([1,2,3,4]))

In [181]:
a

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [182]:
# convert tensor to numpy array
np.array(a)

array([1, 2, 3, 4])

In [183]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [184]:
type(np.array(a))

numpy.ndarray

**finding access to GPUs**

In [185]:
tf.config.list_physical_devices

<function tensorflow.python.framework.config.list_physical_devices>