In [1]:
import tensorflow as tf

**tensor basics**

In [4]:
#initialization of tesnsors
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
x=tf.constant([[1,2,3],[4,5,6]])

In [6]:
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
x=tf.ones((3,3))

In [8]:
# x=tf.zeros((2,3))

In [11]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
x=tf.random.normal((3,3), mean=0,stddev=1)

In [13]:
x


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.23765425,  0.18655635, -0.39638716],
       [-2.0507765 ,  0.04418639, -0.7675763 ],
       [-2.1487248 , -0.78624564,  0.99775296]], dtype=float32)>

In [14]:
y=tf.eye(3)  #identity matrix

In [15]:
y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [16]:
z=tf.random.normal((3,3), mean=0,stddev=1)  #standard distributiuon

In [17]:
z

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8491039 , -1.3612994 , -1.0411756 ],
       [-1.6088353 ,  0.7637353 , -1.0121435 ],
       [-1.9107994 ,  0.79017955,  0.47715694]], dtype=float32)>

In [18]:
x=tf.random.uniform((1,3), minval=0, maxval=4)
x  #random distribution

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3.2460322 , 1.8622742 , 0.37319756]], dtype=float32)>

In [19]:
x=tf.range(8)
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [20]:
x=tf.range(start=1, limit=20,delta=3)

In [21]:
x

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19], dtype=int32)>

In [22]:
x=tf.cast(x,dtype=tf.float64)

In [23]:
x

<tf.Tensor: shape=(7,), dtype=float64, numpy=array([ 1.,  4.,  7., 10., 13., 16., 19.])>

In [24]:
x=tf.constant([1,2,3])
y=tf.constant([3,4,5])
z=tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8], dtype=int32)>

In [26]:
z=x+y

In [27]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8], dtype=int32)>

In [28]:
z=tf.divide(x,y)

In [29]:
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.33333333, 0.5       , 0.6       ])>

In [30]:
z=tf.tensordot(x,y,axes=1)  #dot product

In [31]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=26>

In [32]:
#matrix multiplication
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
#both are equivalent can do any one of these
z=x@y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 2.0701659 ,  1.0152212 , -0.10126853, -0.06372142],
       [-2.781519  , -1.4164598 , -1.0076536 , -3.3815212 ]],
      dtype=float32)>

In [34]:
x=tf.constant([0,1,2,3,4,5,4,2,1,1])
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 4, 2, 1, 1], dtype=int32)>

In [35]:
 x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 4, 1], dtype=int32)>

In [36]:
x[::-1]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 2, 4, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [37]:
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)

In [38]:
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

In [45]:
#reshaping

x=tf.range(9)
x=tf.reshape(x,(1,9))

In [44]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [69]:
#create two random(but the same)tensors
random1=tf.random.Generator.from_seed(42) #set seed for reproductibility
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))

random1,random2
#change seed to change values

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [70]:
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [71]:
#create two random(but not the same)tensors
random1=tf.random.Generator.from_seed(42) #set seed for reproductibility
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(7)
random2=random2.normal(shape=(3,2))

random1,random2
#change seed to change values
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [73]:
#shuffle the order of elements in a tensor
#so that machine learns better and learn both type of imaghes at the same time
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [6,7]])

In [74]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 6,  7]], dtype=int32)>

In [82]:
#shuffling data

tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 6,  7]], dtype=int32)>

In [89]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)
 # its fixed now

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 6,  7]], dtype=int32)>